# Generated by Django 3.2.6 on 2021-08-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sent_mail',
            new_name='SentMail',
        ),
    ]
