# Generated by Django 3.2.6 on 2021-08-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_alter_emailtemplate_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentmail',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sends_emails', to='mailer.emailtemplate', verbose_name='Шаблон'),
        ),
    ]
