# Generated by Django 3.2.6 on 2021-08-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_sentmail_template'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentMail',
            new_name='SentEmail',
        ),
    ]
