# Generated by Django 3.2.6 on 2021-08-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_rename_sentmail_sentemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='subject', max_length=50, verbose_name='Тема письма'),
            preserve_default=False,
        ),
    ]
