# Generated by Django 3.2.6 on 2021-08-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0009_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='email',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамилия'),
        ),
    ]
