# Generated by Django 3.2.6 on 2021-08-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_auto_20210815_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentemail',
            options={'ordering': ['-send_date'], 'verbose_name': 'Отправленное письмо', 'verbose_name_plural': 'Отправленные письма'},
        ),
    ]
